TITLE			= 'Space Odyssey'
VER				= '0.0.1'
#RENDER			= '--terminal'
RENDER			= '--blocky'
SCREEN_WIDTH	= 129
SCREEN_HEIGHT	= 40
VIEWPORT_WIDTH	= 129
VIEWPORT_HEIGHT = 40
MAP_SIZE		= 129
MAX_ZOOM		= 10
FPS				= 20
#TILE_SET		= 'assets/unknown_inrow.png'
TILE_SET		= 'assets/arial10x10.png'
#TILE_SET		= 'assets/test.png'
#TILE_SET		= 'assets/terminal.png'
#TILE_SET		= 'assets/vidumec_15x15.png'
