TITLE			= 'Space Odyssey'
VER				= '0.0.1'
RENDER			= '--terminal'
#RENDER			= '--blocky'
SCREEN_WIDTH	= 100
SCREEN_HEIGHT	= 100
FPS				= 20
MAP_WIDTH		= 65
MAP_HEIGHT		= 65
#TILE_SET		= 'assets/unknown_inrow.png'
TILE_SET		= 'assets/arial10x10.png'
#TILE_SET		= 'assets/test.png'
#TILE_SET		= 'assets/terminal.png'
#TILE_SET		= 'assets/vidumec_15x15.png'
